[package]
name = "yacht"
version = "0.1.0"
authors = ["tracyspacy"]
license = "MIT"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
crossterm = "0.27.0"
ratatui = "0.25.0"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"
chrono = "0.4.31"
